server:
  port: 9091
  servlet:
    context-path: /ECommerceStore

spring:
  application:
    name: ECommerceStore
  datasource:
    url: jdbc:postgresql://localhost:5432/EcommerceStore
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

